// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// label_components_6N_rcpp
IntegerVector label_components_6N_rcpp(LogicalVector flat_mask, IntegerVector dims);
RcppExport SEXP _neuroarchive_label_components_6N_rcpp(SEXP flat_maskSEXP, SEXP dimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type flat_mask(flat_maskSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    rcpp_result_gen = Rcpp::wrap(label_components_6N_rcpp(flat_mask, dims));
    return rcpp_result_gen;
END_RCPP
}
// poisson_disk_sample_component_rcpp
IntegerMatrix poisson_disk_sample_component_rcpp(IntegerMatrix component_vox_coords_0based, double radius_vox_sq, int component_seed);
RcppExport SEXP _neuroarchive_poisson_disk_sample_component_rcpp(SEXP component_vox_coords_0basedSEXP, SEXP radius_vox_sqSEXP, SEXP component_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type component_vox_coords_0based(component_vox_coords_0basedSEXP);
    Rcpp::traits::input_parameter< double >::type radius_vox_sq(radius_vox_sqSEXP);
    Rcpp::traits::input_parameter< int >::type component_seed(component_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_disk_sample_component_rcpp(component_vox_coords_0based, radius_vox_sq, component_seed));
    return rcpp_result_gen;
END_RCPP
}
// sobel3d_magnitude_rcpp
NumericVector sobel3d_magnitude_rcpp(NumericVector vol);
RcppExport SEXP _neuroarchive_sobel3d_magnitude_rcpp(SEXP volSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vol(volSEXP);
    rcpp_result_gen = Rcpp::wrap(sobel3d_magnitude_rcpp(vol));
    return rcpp_result_gen;
END_RCPP
}
// get_openmp_threads
int get_openmp_threads();
RcppExport SEXP _neuroarchive_get_openmp_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_openmp_threads());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neuroarchive_label_components_6N_rcpp", (DL_FUNC) &_neuroarchive_label_components_6N_rcpp, 2},
    {"_neuroarchive_poisson_disk_sample_component_rcpp", (DL_FUNC) &_neuroarchive_poisson_disk_sample_component_rcpp, 3},
    {"_neuroarchive_sobel3d_magnitude_rcpp", (DL_FUNC) &_neuroarchive_sobel3d_magnitude_rcpp, 1},
    {"_neuroarchive_get_openmp_threads", (DL_FUNC) &_neuroarchive_get_openmp_threads, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_neuroarchive(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
