# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

label_components_6N_rcpp <- function(flat_mask, dims) {
    .Call('_neuroarchive_label_components_6N_rcpp', PACKAGE = 'neuroarchive', flat_mask, dims)
}

poisson_disk_sample_component_rcpp <- function(component_vox_coords_0based, radius_vox_sq, component_seed) {
    .Call('_neuroarchive_poisson_disk_sample_component_rcpp', PACKAGE = 'neuroarchive', component_vox_coords_0based, radius_vox_sq, component_seed)
}

hrbf_atoms_rcpp <- function(mask_xyz_world, centres_xyz_world, sigma_vec_mm, kernel_type, value_threshold = 1e-8) {
    .Call('_neuroarchive_hrbf_atoms_rcpp', PACKAGE = 'neuroarchive', mask_xyz_world, centres_xyz_world, sigma_vec_mm, kernel_type, value_threshold)
}

omp_encode_rcpp <- function(signal_y, dict_D, residual_norm_sq_tol, max_active_atoms_L) {
    .Call('_neuroarchive_omp_encode_rcpp', PACKAGE = 'neuroarchive', signal_y, dict_D, residual_norm_sq_tol, max_active_atoms_L)
}

quantize_voxel_block_rcpp <- function(block, bits, method, center) {
    .Call('_neuroarchive_quantize_voxel_block_rcpp', PACKAGE = 'neuroarchive', block, bits, method, center)
}

#' Fast 3D Sobel Gradient Magnitude
#'
#' Computes 3D Sobel gradient magnitude with OpenMP acceleration.
#' This provides 30-100× speedup over pure R implementation.
#' 
#' Optimized version that addresses:
#' \itemize{
#'   \item Integer overflow on very large volumes (>2GB)
#'   \item NumericVector bounds checking overhead  
#'   \item Redundant weight recomputation
#'   \item Efficient single-pass neighborhood traversal
#' }
#'
#' @param vol Numeric 3D array
#' @return Numeric 3D array of gradient magnitudes
#' @export
sobel3d_magnitude_rcpp <- function(vol) {
    .Call('_neuroarchive_sobel3d_magnitude_rcpp', PACKAGE = 'neuroarchive', vol)
}

#' Get OpenMP thread count
#' @export
get_openmp_threads <- function() {
    .Call('_neuroarchive_get_openmp_threads', PACKAGE = 'neuroarchive')
}

forward_lift_rcpp <- function(data_masked_morton_ordered, mask_flat_morton_ordered, mask_dims, levels, scaling_factors_per_level) {
    .Call('_neuroarchive_forward_lift_rcpp', PACKAGE = 'neuroarchive', data_masked_morton_ordered, mask_flat_morton_ordered, mask_dims, levels, scaling_factors_per_level)
}

inverse_lift_rcpp <- function(root_coeff, detail_coeffs_by_level, mask_flat_morton_ordered, mask_dims, levels, scaling_factors_per_level) {
    .Call('_neuroarchive_inverse_lift_rcpp', PACKAGE = 'neuroarchive', root_coeff, detail_coeffs_by_level, mask_flat_morton_ordered, mask_dims, levels, scaling_factors_per_level)
}

morton_indices_to_hash_rcpp <- function(voxelIdx) {
    .Call('_neuroarchive_morton_indices_to_hash_rcpp', PACKAGE = 'neuroarchive', voxelIdx)
}

