# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

label_components_6N_rcpp <- function(flat_mask, dims) {
    .Call(`_neuroarchive_label_components_6N_rcpp`, flat_mask, dims)
}

poisson_disk_sample_component_rcpp <- function(component_vox_coords_0based, radius_vox_sq, component_seed) {
    .Call(`_neuroarchive_poisson_disk_sample_component_rcpp`, component_vox_coords_0based, radius_vox_sq, component_seed)
}

